# Generated by Django 4.0.5 on 2022-09-02 08:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0002_alter_comment_date_alter_details_coins_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 2, 11, 38, 27, 509762, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='details',
            name='subscription_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 2, 11, 38, 27, 507763, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='messages',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 2, 11, 38, 27, 510762, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='request',
            name='requested_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 2, 11, 38, 27, 507763, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sale',
            name='transaction_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 2, 11, 38, 27, 510762, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 2, 11, 38, 27, 508763, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Hash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=1050)),
                ('num', models.IntegerField(unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
